name: "[Auto] Merge Dependabot Updates"

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  automerge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    uses: istic/shared-workflows/.github/workflows/auto-merge-dependabot.yml@main
    permissions:
      pull-requests: write
      contents: write
